export const MX_STATES = [
  'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche',
  'Chiapas', 'Chihuahua', 'Ciudad de México', 'Coahuila', 'Colima',
  'Durango', 'Estado de México', 'Guanajuato', 'Guerrero', 'Hidalgo',
  'Jalisco', 'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca',
  'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 'Sinaloa',
  'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz',
  'Yucatán', 'Zacatecas',
];

export const MX_MUNICIPALITIES = {
  'Aguascalientes': ['Aguascalientes', 'Asientos', 'Calvillo', 'Cosío', 'Jesús María', 'Pabellón de Arteaga', 'Rincón de Romos', 'San José de Gracia', 'Tepezalá', 'El Llano', 'San Francisco de los Romo'],
  'Baja California': ['Ensenada', 'Mexicali', 'Tecate', 'Tijuana', 'Playas de Rosarito'],
  'Baja California Sur': ['Comondú', 'Mulegé', 'La Paz', 'Los Cabos', 'Loreto'],
  'Campeche': ['Calkiní', 'Campeche', 'Carmen', 'Champotón', 'Hecelchakán', 'Hopelchén', 'Palizada', 'Tenabo', 'Escárcega', 'Calakmul', 'Candelaria'],
  'Chiapas': ['Tuxtla Gutiérrez', 'San Cristóbal de las Casas', 'Tapachula', 'Comitán', 'Chiapa de Corzo', 'Ocosingo', 'Palenque', 'Tonalá'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Cuauhtémoc', 'Parral', 'Nuevo Casas Grandes', 'Camargo', 'Jiménez'],
  'Ciudad de México': ['Álvaro Obregón', 'Azcapotzalco', 'Benito Juárez', 'Coyoacán', 'Cuajimalpa', 'Cuauhtémoc', 'Gustavo A. Madero', 'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras', 'Miguel Hidalgo', 'Milpa Alta', 'Tláhuac', 'Tlalpan', 'Venustiano Carranza', 'Xochimilco'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña', 'Ramos Arizpe', 'Frontera'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez', 'Armería', 'Comala', 'Coquimatlán', 'Cuauhtémoc', 'Ixtlahuacán', 'Minatitlán'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo', 'Nuevo Ideal', 'Pueblo Nuevo', 'Canatlán', 'Tlahualilo'],
  'Estado de México': ['Ecatepec', 'Nezahualcóyotl', 'Toluca', 'Tlalnepantla', 'Naucalpan', 'Chimalhuacán', 'Ixtapaluca', 'Tultitlán', 'Cuautitlán Izcalli', 'Texcoco', 'Nicolás Romero', 'Atizapán de Zaragoza'],
  'Guanajuato': ['Guanajuato', 'León', 'Irapuato', 'Celaya', 'Salamanca', 'Silao', 'San Miguel de Allende', 'Pénjamo', 'Dolores Hidalgo', 'Acámbaro', 'Valle de Santiago', 'Abasolo'],
  'Guerrero': ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo', 'Taxco', 'Tlapa de Comonfort'],
  'Hidalgo': ['Pachuca', 'Tulancingo', 'Tula de Allende', 'Actopan', 'Ixmiquilpan', 'Huejutla de Reyes', 'Tizayuca'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'San Pedro Tlaquepaque', 'Tonalá', 'Tlajomulco', 'Puerto Vallarta', 'Lagos de Moreno', 'El Salto'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Apatzingán', 'Lázaro Cárdenas', 'Hidalgo', 'Zitácuaro'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla', 'Temixco', 'Yautepec', 'Jojutla', 'Ayala'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla', 'Compostela', 'Ixtlán del Río', 'Acaponeta'],
  'Nuevo León': ['Monterrey', 'Guadalupe', 'San Nicolás de los Garza', 'Apodaca', 'General Escobedo', 'Santa Catarina', 'San Pedro Garza García', 'Juárez', 'García'],
  'Oaxaca': ['Oaxaca de Juárez', 'Salina Cruz', 'Juchitán', 'Tuxtepec', 'Huatulco', 'Heroica Ciudad de Huajuapan de León'],
  'Puebla': ['Puebla', 'Tehuacán', 'San Martín Texmelucan', 'Atlixco', 'Izúcar de Matamoros', 'Cholula', 'Teziutlán'],
  'Querétaro': ['Querétaro', 'San Juan del Río', 'El Marqués', 'Corregidora', 'Pedro Escobedo', 'Cadereyta de Montes'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Chetumal', 'Cozumel', 'Tulum', 'Bacalar', 'Puerto Morelos'],
  'San Luis Potosí': ['San Luis Potosí', 'Soledad de Graciano Sánchez', 'Ciudad Valles', 'Matehuala', 'Rioverde', 'Tamazunchale'],
  'Sinaloa': ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave', 'Navolato', 'Guamúchil'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'San Luis Río Colorado', 'Navojoa', 'Guaymas', 'Caborca'],
  'Tabasco': ['Villahermosa', 'Cárdenas', 'Comalcalco', 'Paraíso', 'Macuspana', 'Tenosique'],
  'Tamaulipas': ['Reynosa', 'Matamoros', 'Nuevo Laredo', 'Tampico', 'Ciudad Madero', 'Altamira', 'Victoria'],
  'Tlaxcala': ['Tlaxcala', 'Apizaco', 'Huamantla', 'Chiautempan', 'Tlaxco', 'Calpulalpan'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Córdoba', 'Orizaba', 'Minatitlán', 'Poza Rica', 'Tuxpan'],
  'Yucatán': ['Mérida', 'Valladolid', 'Tizimín', 'Progreso', 'Umán', 'Kanasín', 'Motul'],
  'Zacatecas': ['Zacatecas', 'Guadalupe', 'Fresnillo', 'Jerez', 'Loreto', 'Tlaltenango', 'Sombrerete'],
};
