tunnel: 4ba8e093-5994-49bd-b90a-f3c7853f5bc0
credentials-file: /etc/cloudflared/4ba8e093-5994-49bd-b90a-f3c7853f5bc0.json

ingress:
  - hostname: tiendatap.com
    service: http://app:3000
  - hostname: www.tiendatap.com
    service: http://app:3000
  - hostname: api.tiendatap.com
    service: http://app:3000
  - service: http_status:404
