networks:
  catalogo-network:
    name: catalogo-network
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env